# .github/workflows/test.yml
name: Test Site

on:
  pull_request:
    paths:
      - "site/**"

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: site/package-lock.json
      - name: Lint
        working-directory: site
        run: |
          npm ci
          npm run lint